### PR TITLE
Add architecture content

### PR DESCRIPTION
**Pull request by valeriocos**
This code includes a new section called `Architecture`, that contains the details of some GrimoireLab components (Perceval, Graal, Arthur, SortingHat) and prepare the sub-sections for
other ones.

### CODE REVIEW

**Comment by valeriocos** [comment]
please @jsmanrique have a look, thanks

**Comment by GeorgLink** [comment]
Thanks @valeriocos 

This would be the second section per our outline (#1), I assume. Why do you call it a "new section"?

There is too much content at once for me to review it. If you would like me to consider this, maybe there is a way to split this up into smaller pull requests?

**Comment by valeriocos** [comment]
You're welcome @GeorgLink 

> This would be the second section per our outline (#1), I assume. Why do you call it a "new section"?

To isolate the new content, I add it the section `Architecture`, which wasn't present before. However, I can include the content directly to  `GrimoireLab Architecture and Data Workflow`.

> There is too much content at once for me to review it. If you would like me to consider this, maybe there is a way to split this up into smaller pull requests?

The content can be splitted, it's not a problem. However to avoid bottlenecks during the review phase, we can merge the PR with the current content, and later you can submit other PRs to polish/reorganize/modify this content. I guess that after these cycles, the modifications will be smaller and we can start using the review process. In any case, I'm open to any solution, so feel free to decide.

**Comment by GeorgLink** [comment]
I assume @jsmanrique is busy preparing for tomorrow's big meeting. Let's see what he thinks.

**Comment by jsmanrique** [comment]
I think we can merge it and refine the users guide with the content submitted here, instead of making the review process longer. What do you think?

**Comment by GeorgLink** [comment]
Okay. I'm okay with Valerio's and Manrique's proposed path forward.

**Pull request merged**
