### PR TITLE
add docker and pip instructions

### PR DESCRIPTION
**Pull request by GeorgLink**
Adding instructions for docker and pip

Still missing information on how to run the `pip` installed GrimoireLab

@valeriocos could you add that information?

### CODE REVIEW

**Comment by jsmanrique** [comment]
ILGTM

**Review by valeriocos — APPROVED** [review]
LGTM

**Comment by valeriocos** [comment]
@GeorgLink I'll prepare another PR to complete that section

**Comment by GeorgLink** [comment]
Thank you!

**Pull request merged**
